import { Dimensions } from "react-native";
import { IData } from "../components/movieCard";

export const data : IData[] = [{title:'lorem ipsum', content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur nisl metus. Ut auctor dui ante, a hendrerit augue interdum a. Praesent non tempor arcu. Curabitur et viverra nunc. Quisque interdum est non nisi lobortis, id rhoncus eros molestie. Integer mollis mauris nunc, condimentum ultricies nibh dictum sed. Morbi aliquet semper lectus sit amet porta.

    Mauris nec elementum justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ornare, purus vel iaculis aliquam, tellus magna vehicula urna, id volutpat diam odio sit amet nulla. Vivamus semper facilisis nunc. Curabitur lobortis eros a lobortis malesuada. Vestibulum orci magna, sagittis sed nisl ut, egestas tincidunt ligula. Sed tincidunt quam sed justo gravida fermentum. Ut at est id nibh varius laoreet vitae eget odio. Aliquam facilisis mollis varius. Sed ut risus lobortis, posuere erat tincidunt, pulvinar nibh. Mauris ac turpis lobortis, pellentesque ante quis, rutrum neque. Aenean eu sagittis felis. Nunc fringilla sit amet odio eu tristique.
    
    Pellentesque accumsan eros in tincidunt tincidunt. Maecenas mattis ante id enim egestas, vitae lacinia leo iaculis. Suspendisse potenti. Sed lobortis vulputate pharetra. Aliquam erat volutpat. Nam congue faucibus neque, vel laoreet nulla varius sit amet. Duis interdum lacus dui, sagittis luctus magna sagittis quis. Morbi in sagittis quam. Pellentesque ex leo, malesuada id augue vitae, tempus consequat eros. Aliquam eget nibh quis velit tristique tempus sit amet hendrerit augue. Duis maximus dui sit amet eros vehicula sollicitudin. Nam sit amet sodales metus, ut pharetra justo.
    
    Nam sagittis vel mauris a sodales. Nulla nec tempor turpis. Nunc tempus scelerisque est. Cras varius dui ut metus iaculis iaculis. Pellentesque non iaculis leo, et eleifend odio. Aenean tristique consequat felis, quis vehicula lacus lobortis in. Aliquam hendrerit, libero malesuada ornare maximus, ex nibh hendrerit metus, ut volutpat lacus mauris ac lacus. Aenean condimentum id velit sit amet consectetur. Suspendisse a finibus neque, vitae accumsan ipsum. Sed sed leo magna. Vestibulum elementum luctus sapien sit amet interdum. Suspendisse eget risus non ex egestas laoreet.
    
    Duis faucibus, magna sit amet consequat dignissim, purus odio gravida sapien, et finibus odio diam porta massa. Etiam non velit et risus maximus bibendum. Mauris dignissim lacinia porttitor. Ut vitae est sit amet libero ullamcorper consequat. Proin sit amet finibus lectus. Aenean et mollis purus. Suspendisse varius nisi eu est ultrices, eget ultrices augue hendrerit. Ut luctus lorem metus, nec gravida eros dapibus vel. Aliquam pulvinar justo non tellus interdum, vitae dictum ligula auctor. Aliquam suscipit est non enim auctor, eu malesuada nulla pharetra. Pellentesque ut turpis sit amet lorem rhoncus faucibus sed facilisis ante.`, image:'https://i.pinimg.com/originals/2f/b2/41/2fb241498d55157668ca09f6175a9636.jpg'},
        {title:'lorem ipsum', content:'Lorem Ipsum ', image:'https://i.pinimg.com/originals/2f/b2/41/2fb241498d55157668ca09f6175a9636.jpg'},
        {title:'lorem ipsum', content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur nisl metus. Ut auctor dui ante, a hendrerit augue interdum a. Praesent non tempor arcu. Curabitur et viverra nunc. Quisque interdum est non nisi lobortis, id rhoncus eros molestie. Integer mollis mauris nunc, condimentum ultricies nibh dictum sed. Morbi aliquet semper lectus sit amet porta.
    
    Mauris nec elementum justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ornare, purus vel iaculis aliquam, tellus magna vehicula urna, id volutpat diam odio sit amet nulla. Vivamus semper facilisis nunc. Curabitur lobortis eros a lobortis malesuada. Vestibulum orci magna, sagittis sed nisl ut, egestas tincidunt ligula. Sed tincidunt quam sed justo gravida fermentum. Ut at est id nibh varius laoreet vitae eget odio. Aliquam facilisis mollis varius. Sed ut risus lobortis, posuere erat tincidunt, pulvinar nibh. Mauris ac turpis lobortis, pellentesque ante quis, rutrum neque. Aenean eu sagittis felis. Nunc fringilla sit amet odio eu tristique.
    
    Pellentesque accumsan eros in tincidunt tincidunt. Maecenas mattis ante id enim egestas, vitae lacinia leo iaculis. Suspendisse potenti. Sed lobortis vulputate pharetra. Aliquam erat volutpat. Nam congue faucibus neque, vel laoreet nulla varius sit amet. Duis interdum lacus dui, sagittis luctus magna sagittis quis. Morbi in sagittis quam. Pellentesque ex leo, malesuada id augue vitae, tempus consequat eros. Aliquam eget nibh quis velit tristique tempus sit amet hendrerit augue. Duis maximus dui sit amet eros vehicula sollicitudin. Nam sit amet sodales metus, ut pharetra justo.
    
    Nam sagittis vel mauris a sodales. Nulla nec tempor turpis. Nunc tempus scelerisque est. Cras varius dui ut metus iaculis iaculis. Pellentesque non iaculis leo, et eleifend odio. Aenean tristique consequat felis, quis vehicula lacus lobortis in. Aliquam hendrerit, libero malesuada ornare maximus, ex nibh hendrerit metus, ut volutpat lacus mauris ac lacus. Aenean condimentum id velit sit amet consectetur. Suspendisse a finibus neque, vitae accumsan ipsum. Sed sed leo magna. Vestibulum elementum luctus sapien sit amet interdum. Suspendisse eget risus non ex egestas laoreet.
    
    Duis faucibus, magna sit amet consequat dignissim, purus odio gravida sapien, et finibus odio diam porta massa. Etiam non velit et risus maximus bibendum. Mauris dignissim lacinia porttitor. Ut vitae est sit amet libero ullamcorper consequat. Proin sit amet finibus lectus. Aenean et mollis purus. Suspendisse varius nisi eu est ultrices, eget ultrices augue hendrerit. Ut luctus lorem metus, nec gravida eros dapibus vel. Aliquam pulvinar justo non tellus interdum, vitae dictum ligula auctor. Aliquam suscipit est non enim auctor, eu malesuada nulla pharetra. Pellentesque ut turpis sit amet lorem rhoncus faucibus sed facilisis ante.`, image:'https://i.pinimg.com/originals/2f/b2/41/2fb241498d55157668ca09f6175a9636.jpg'},
        {title:'lorem ipsum', content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur nisl metus. Ut auctor dui ante, a hendrerit augue interdum a. Praesent non tempor arcu. Curabitur et viverra nunc. Quisque interdum est non nisi lobortis, id rhoncus eros molestie. Integer mollis mauris nunc, condimentum ultricies nibh dictum sed. Morbi aliquet semper lectus sit amet porta.
    
    Mauris nec elementum justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ornare, purus vel iaculis aliquam, tellus magna vehicula urna, id volutpat diam odio sit amet nulla. Vivamus semper facilisis nunc. Curabitur lobortis eros a lobortis malesuada. Vestibulum orci magna, sagittis sed nisl ut, egestas tincidunt ligula. Sed tincidunt quam sed justo gravida fermentum. Ut at est id nibh varius laoreet vitae eget odio. Aliquam facilisis mollis varius. Sed ut risus lobortis, posuere erat tincidunt, pulvinar nibh. Mauris ac turpis lobortis, pellentesque ante quis, rutrum neque. Aenean eu sagittis felis. Nunc fringilla sit amet odio eu tristique.
    
    Pellentesque accumsan eros in tincidunt tincidunt. Maecenas mattis ante id enim egestas, vitae lacinia leo iaculis. Suspendisse potenti. Sed lobortis vulputate pharetra. Aliquam erat volutpat. Nam congue faucibus neque, vel laoreet nulla varius sit amet. Duis interdum lacus dui, sagittis luctus magna sagittis quis. Morbi in sagittis quam. Pellentesque ex leo, malesuada id augue vitae, tempus consequat eros. Aliquam eget nibh quis velit tristique tempus sit amet hendrerit augue. Duis maximus dui sit amet eros vehicula sollicitudin. Nam sit amet sodales metus, ut pharetra justo.
    
    Nam sagittis vel mauris a sodales. Nulla nec tempor turpis. Nunc tempus scelerisque est. Cras varius dui ut metus iaculis iaculis. Pellentesque non iaculis leo, et eleifend odio. Aenean tristique consequat felis, quis vehicula lacus lobortis in. Aliquam hendrerit, libero malesuada ornare maximus, ex nibh hendrerit metus, ut volutpat lacus mauris ac lacus. Aenean condimentum id velit sit amet consectetur. Suspendisse a finibus neque, vitae accumsan ipsum. Sed sed leo magna. Vestibulum elementum luctus sapien sit amet interdum. Suspendisse eget risus non ex egestas laoreet.
    
    Duis faucibus, magna sit amet consequat dignissim, purus odio gravida sapien, et finibus odio diam porta massa. Etiam non velit et risus maximus bibendum. Mauris dignissim lacinia porttitor. Ut vitae est sit amet libero ullamcorper consequat. Proin sit amet finibus lectus. Aenean et mollis purus. Suspendisse varius nisi eu est ultrices, eget ultrices augue hendrerit. Ut luctus lorem metus, nec gravida eros dapibus vel. Aliquam pulvinar justo non tellus interdum, vitae dictum ligula auctor. Aliquam suscipit est non enim auctor, eu malesuada nulla pharetra. Pellentesque ut turpis sit amet lorem rhoncus faucibus sed facilisis ante.`, image:'https://i.pinimg.com/originals/2f/b2/41/2fb241498d55157668ca09f6175a9636.jpg'},
        {title:'lorem ipsum', content:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce consectetur nisl metus. Ut auctor dui ante, a hendrerit augue interdum a. Praesent non tempor arcu. Curabitur et viverra nunc. Quisque interdum est non nisi lobortis, id rhoncus eros molestie. Integer mollis mauris nunc, condimentum ultricies nibh dictum sed. Morbi aliquet semper lectus sit amet porta.
    
    Mauris nec elementum justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus ornare, purus vel iaculis aliquam, tellus magna vehicula urna, id volutpat diam odio sit amet nulla. Vivamus semper facilisis nunc. Curabitur lobortis eros a lobortis malesuada. Vestibulum orci magna, sagittis sed nisl ut, egestas tincidunt ligula. Sed tincidunt quam sed justo gravida fermentum. Ut at est id nibh varius laoreet vitae eget odio. Aliquam facilisis mollis varius. Sed ut risus lobortis, posuere erat tincidunt, pulvinar nibh. Mauris ac turpis lobortis, pellentesque ante quis, rutrum neque. Aenean eu sagittis felis. Nunc fringilla sit amet odio eu tristique.
    
    Pellentesque accumsan eros in tincidunt tincidunt. Maecenas mattis ante id enim egestas, vitae lacinia leo iaculis. Suspendisse potenti. Sed lobortis vulputate pharetra. Aliquam erat volutpat. Nam congue faucibus neque, vel laoreet nulla varius sit amet. Duis interdum lacus dui, sagittis luctus magna sagittis quis. Morbi in sagittis quam. Pellentesque ex leo, malesuada id augue vitae, tempus consequat eros. Aliquam eget nibh quis velit tristique tempus sit amet hendrerit augue. Duis maximus dui sit amet eros vehicula sollicitudin. Nam sit amet sodales metus, ut pharetra justo.
    
    Nam sagittis vel mauris a sodales. Nulla nec tempor turpis. Nunc tempus scelerisque est. Cras varius dui ut metus iaculis iaculis. Pellentesque non iaculis leo, et eleifend odio. Aenean tristique consequat felis, quis vehicula lacus lobortis in. Aliquam hendrerit, libero malesuada ornare maximus, ex nibh hendrerit metus, ut volutpat lacus mauris ac lacus. Aenean condimentum id velit sit amet consectetur. Suspendisse a finibus neque, vitae accumsan ipsum. Sed sed leo magna. Vestibulum elementum luctus sapien sit amet interdum. Suspendisse eget risus non ex egestas laoreet.
    
    Duis faucibus, magna sit amet consequat dignissim, purus odio gravida sapien, et finibus odio diam porta massa. Etiam non velit et risus maximus bibendum. Mauris dignissim lacinia porttitor. Ut vitae est sit amet libero ullamcorper consequat. Proin sit amet finibus lectus. Aenean et mollis purus. Suspendisse varius nisi eu est ultrices, eget ultrices augue hendrerit. Ut luctus lorem metus, nec gravida eros dapibus vel. Aliquam pulvinar justo non tellus interdum, vitae dictum ligula auctor. Aliquam suscipit est non enim auctor, eu malesuada nulla pharetra. Pellentesque ut turpis sit amet lorem rhoncus faucibus sed facilisis ante.`, image:'https://i.pinimg.com/originals/2f/b2/41/2fb241498d55157668ca09f6175a9636.jpg'},
       ]

export const { width, height } = Dimensions.get('screen');
export const _itemwidth = width* 0.6
export const _itemheight = 300
export const _spacing = 8 
export const _itemfullsize = _itemwidth + _spacing